include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_returning_null_for_future: true
    prefer_void_to_null: true
    always_require_non_null_named_parameters: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    prefer_initializing_formals: true
    prefer_typing_uninitialized_variables: true
    avoid_print: true
    prefer_final_locals: true
    sort_constructors_first: true
    avoid_function_literals_in_foreach_calls: false
    unawaited_futures: true
    non_constant_identifier_names: false
